batch_size: 256
consistency_loss_weight: 1.0
eval_policy_every: 5
gamma: 0.99
hidden_dim: 256
horizon: 5
image_observations: false
latent_dim: 32
learning_rate: 1e-3
learning_rate_actor: 1e-4
max_episode_length: 600
name: TD-MPC (default)
noisy_action_experience: true
noisy_action_training: true
num_episodes_per_round: 3
optimization_iterations: 10
reward_loss_weight: 0.5
sample_size: 256
sampler: predictive-sampling
sampling_noise: 0.3
time_lambda: 0.1
training_rounds: 200
training_steps_per_round: 100
value_loss_weight: 0.2
